import "./styles.scss";
import { Montserrat } from "next/font/google";

import NavBar from "@/components/navbar/NavBar";
import Footer from "@/components/footer/Footer";
import Button from "@/components/button/Button";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-slate-500 dark:text-white`}>
        <main className="container wrapper">
          <NavBar />
          {children}
          <Button title="Hello world" />
        </main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
