import "./styles.scss";
import { Montserrat } from "next/font/google";

import Navigation from "@/components/navigation/Navigation";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} dark:text-white`}>
        <Navigation />
        <main>
          {children}
          {/* <Button title="Hello world" />
          <Poster title="Poster 1" description="Hello world" /> */}
        </main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
